import type { Metadata } from "next";
import "./global.css";
import Header from "@/frontend/components/header-default/Header";
import Footer from "@/frontend/components/footer-default/Footer";

export const metadata: Metadata = {
  title: "King Bites",
  description: "Generated by create next page",
  
  icons: {
    
    icon: '/assets/banner.jpeg', // Certifique-se que este arquivo exista em public/favicon/
    // Para adicionar outros formatos ou ícones específicos:
    // apple: '/favicon/apple-touch-icon.png', // Se tiver um ícone para dispositivos Apple
    // shortcut: {
    //   rel: 'shortcut icon',
    //   href: '/favicon/favicon.png', // Se preferir usar .png como ícone principal
    // },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* A meta tag viewport geralmente é colocada aqui, se ainda não estiver no seu global.css */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="layoutContainer">
        <Header />
        <main className="mainContent pageContainer">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}