"use client"

import React, { createContext, useState, useContext, useEffect, ReactNode } from 'react';

export type Language = 'pt-BR' | 'en-US';

type LanguageContextType = {
    language: Language;
    setLanguage: (lang: Language) => void;
    translations: Record<string, string>;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translationMap: Record<Language, Record<string, string>> = {
    'pt-BR': {
        'inicio': 'Início',
        'cardapio': 'Cardápio',
        'sobre': 'Sobre',
        'contato': 'Contato',
        'slogan': 'SABOR BRASILEIRO NOS EUA',
        'descricao': 'Experimente os mais deliciosos lanches com aquele tempero autêntico do Brasil, em um ambiente acolhedor que vai te fazer sentir em casa.',
        'cardapio_completo': 'CARDÁPIO COMPLETO',
        'sabor_real': 'SABOR REAL',
        'sabor_real_desc': 'Lanches artesanais preparados com ingredientes selecionados',
        'ambiente_brasileiro': 'AMBIENTE BRASILEIRO',
        'ambiente_brasileiro_desc': 'Música, decoração e aquele atendimento caloroso do Brasil',
        'pratos_exclusivos': 'PRATOS EXCLUSIVOS',
        'pratos_exclusivos_desc': 'Combinações únicas que só encontra aqui no King Bites',
        'nossos_destaques': 'NOSSOS DESTAQUES',
        'salgadinhos_brasileiros_gallery': 'Salgadinhos brasileiros',
        'x_tudo_hamburguer': 'X-Tudo hambúrguer',
        'frango_com_fritas': 'Frango com fritas',
        'pizza_e_lanche': 'Pizza e lanche',
        'o_que_clientes_dizem': 'O QUE NOSSOS CLIENTES DIZEM',
        'testemunho_cliente': 'O melhor hambúrguer brasileiro que já comi fora do Brasil. Me senti em casa!',
        'nome_cliente': '- João Silva, Cliente desde 2023',
        'slogan_final': 'KING BITES. ONDE O SABOR É VERDADEIRAMENTE REI.',
        'experimente_agora': 'EXPERIMENTE AGORA',
        'cardapio_king_bites': 'CARDÁPIO KING BITES',
        'menu_subtitulo': 'Experimente nossos lanches artesanais com autêntico sabor brasileiro',
        'especial': 'ESPECIAL',
        'combo_especial_king_bites': 'COMBO ESPECIAL KING BITES',
        'combo_especial_desc': 'Experimente nosso combo exclusivo com 3 X-Tudo Burgers, linguiça calabresa grelhada (estilo brasileiro picante), 25 mini salgadinhos brasileiros (coxinha, risoles e mais) e batatas fritas carregadas. Perfeito para compartilhar com amigos e família!',
        'fazer_pedido': 'FAZER PEDIDO',
        'todos': 'Todos',
        'hamburgueres': 'Hambúrgueres',
        'combos': 'Combos',
        'salgadinhos': 'Salgadinhos',
        'bebidas': 'Bebidas',
        'hamburgueres_brasileiros': 'HAMBÚRGUERES BRASILEIROS',
        'hamburgueres_desc': 'Nossos hambúrgueres artesanais são preparados no estilo autêntico brasileiro, com ingredientes frescos e de alta qualidade. Cada hambúrguer vem com uma combinação única de sabores que te transportarão diretamente para as ruas do Brasil.',
        'combos_acompanhamentos': 'COMBOS E ACOMPANHAMENTOS',
        'combos_desc': 'Nossos combos são perfeitos para compartilhar ou para quem quer experimentar uma variedade de sabores. Com opções que combinam nossos lanches favoritos com acompanhamentos deliciosos, você terá uma experiência gastronômica completa.',
        'salgadinhos_brasileiros': 'SALGADINHOS BRASILEIROS',
        'salgadinhos_desc': 'Os salgadinhos são uma parte essencial da culinária brasileira. Oferecemos uma variedade de opções tradicionais, desde coxinhas até enroladinhos de salsicha, todos preparados com receitas autênticas trazidas diretamente do Brasil.',
        'bebidas_titulo': 'BEBIDAS',
        'bebidas_desc': 'Complete sua refeição com nossa seleção de bebidas, incluindo os refrigerantes brasileiros como o famoso Guaraná, que oferece um sabor único e refrescante para acompanhar seus lanches favoritos.',
        'o_que_clientes_dizem_menu': 'O QUE NOSSOS CLIENTES DIZEM',
        'experimente_sabor': 'EXPERIMENTE O SABOR AUTÊNTICO DO BRASIL',
        'experimente_sabor_desc': 'Visite o King Bites hoje ou faça seu pedido online para experimentar os melhores lanches brasileiros nos Estados Unidos!',
        'pedir_agora': 'PEDIR AGORA',
        'sobre_king_bites': 'SOBRE O KING BITES',
        'nossa_historia': 'NOSSA HISTÓRIA',
        'historia_paragrafo1': 'King Bites nasceu de uma verdadeira paixão pela culinária brasileira. Acreditamos que cada mordida deve ser inesquecível — por isso usamos ingredientes frescos, carnes suculentas e receitas originais que transformam qualquer pessoa em fã.',
        'historia_paragrafo2': 'Nossa missão é simples: entregar uma experiência única onde o sabor é rei. Do pão macio ao hambúrguer artesanal e nossos molhos caseiros, cada detalhe é feito com carinho para que você sempre saia satisfeito.',
        'historia_paragrafo3': 'Mais do que apenas uma hamburgueria, somos um ponto de encontro para quem ama boa comida, ambiente descontraído e atendimento de primeira.',
        'historia_paragrafo4': 'King Bites. Onde o sabor é rei.',
        'nossa_missao': 'NOSSA MISSÃO',
        'missao_statement': 'Servir comida artesanal de alta qualidade, proporcionando uma experiência saborosa, acolhedora e memorável para cada cliente — sempre com ingredientes frescos, excelente atendimento e paixão em cada detalhe.',
        'ingredientes_frescos': 'Ingredientes Frescos',
        'ingredientes_frescos_desc': 'Do produtor direto para sua mesa, garantimos frescor e qualidade em cada refeição',
        'chefs_especializados': 'Chefs Especializados',
        'chefs_especializados_desc': 'Preparação artesanal com técnicas exclusivas e conhecimento da culinária brasileira',
        'feito_com_amor': 'Feito com Amor',
        'feito_com_amor_desc': 'Cada lanche é preparado com carinho, como se estivéssemos cozinhando para nossa própria família',
        'cliente_rei': 'Cliente é Rei',
        'cliente_rei_desc': 'Cada cliente é tratado como realeza — com respeito, cuidado e serviço de alta qualidade',
        'excelencia_sempre': 'Excelência Sempre',
        'excelencia_sempre_desc': 'Da nossa cozinha à sua mesa, buscamos nada menos que excelência em tudo o que fazemos',
        'sabores_brasil': 'Sabores do Brasil',
        'sabores_brasil_desc': 'Trazemos a autenticidade da gastronomia brasileira para o coração dos Estados Unidos',
        'nossa_trajetoria': 'NOSSA TRAJETÓRIA',
        'ideia': 'A Ideia',
        'ideia_desc': 'King Bites começa como um sonho de trazer os verdadeiros sabores brasileiros para os EUA.',
        'primeiros_passos': 'Primeiros Passos',
        'primeiros_passos_desc': 'Inauguração da primeira loja, com apenas um pequeno cardápio de hambúrgueres e salgadinhos brasileiros.',
        'expansao_cardapio': 'Expansão do Cardápio',
        'expansao_cardapio_desc': 'Adicionamos novos itens ao menu, incluindo mais opções de salgadinhos e lanches brasileiros.',
        'reconhecimento_local': 'Reconhecimento Local',
        'reconhecimento_local_desc': 'King Bites é reconhecido como uma das melhores hamburguerias brasileiras da região.',
        'presente_futuro': 'Presente e Futuro',
        'presente_futuro_desc': 'Continuamos a crescer e inovar, sempre mantendo a autenticidade e o sabor que nos tornaram famosos.',
        'venha_experimentar': 'VENHA EXPERIMENTAR',
        'venha_experimentar_desc': 'Estamos esperando por você para experimentar o melhor da culinária brasileira nos Estados Unidos. Hambúrgueres artesanais, salgadinhos tradicionais e muito mais!',
        'ver_cardapio': 'VER CARDÁPIO',
        'fale_conosco': 'FALE CONOSCO',
        'contato_subtitulo': 'Tem alguma dúvida ou sugestão? Envie uma mensagem e retornaremos o mais breve possível!',
        'info_contato': 'Informações de Contato',
        'endereco': 'Endereço',
        'endereco_valor': '550 Ferry Street Everett, MA, EUA',
        'telefone': 'Telefone',
        'telefone_valor': '+1 (781) 475-7872',
        'email': 'E-mail',
        'email_valor': 'renata.souza.coelho@hotmail.com',
        'horario_funcionamento': 'Horário de Funcionamento',
        'horario_dias_semana': 'Seg - Qua: 11h às 22h',
        'horario_fim_semana': 'Qui - Sáb: 12h às 20h',
        'redes_sociais': 'Redes Sociais',
        'localizacao_mapa': 'Localização do King Bites',
        'envie_mensagem': 'ENVIE UMA MENSAGEM',
        'seu_nome': 'Seu Nome',
        'nome_placeholder': 'Digite seu nome completo',
        'seu_email': 'Seu Email',
        'email_placeholder': 'exemplo@email.com',
        'sua_mensagem': 'Sua Mensagem',
        'mensagem_placeholder': 'Como podemos ajudar? Escreva sua mensagem aqui...',
        'enviando': 'Enviando...',
        'enviar_mensagem': 'Enviar Mensagem',
        'mensagem_sucesso': 'Mensagem enviada com sucesso! Entraremos em contato em breve.',
        'mensagem_erro': 'Não foi possível enviar sua mensagem. Por favor, tente novamente mais tarde.',
        'perguntas_frequentes': 'PERGUNTAS FREQUENTES',
        'faq1_pergunta': 'Qual é o horário de funcionamento do King Bites?',
        'faq1_resposta': 'Estamos abertos de segunda a sábado, das 11h às 22h, e aos domingos das 12h às 20h.',
        'faq2_pergunta': 'Vocês oferecem opções vegetarianas?',
        'faq2_resposta': 'Sim! Temos várias opções vegetarianas no nosso cardápio, incluindo lanches à base de plantas e salgadinhos de queijo.',
        'faq3_pergunta': 'Posso fazer pedidos para eventos?',
        'faq3_resposta': 'Absolutamente! Oferecemos serviços de catering para eventos de todos os tamanhos. Entre em contato conosco com pelo menos 48 horas de antecedência para discutirmos as opções.',
        'faq4_pergunta': 'Vocês fazem entregas?',
        'faq4_resposta': 'Sim, realizamos entregas através do DoorDash e também oferecemos a opção de retirada no local.',
        'faq5_pergunta': 'Os ingredientes são importados do Brasil?',
        'faq5_resposta': 'Utilizamos uma combinação de ingredientes importados do Brasil e ingredientes locais de alta qualidade para criar a autêntica experiência brasileira.',
        'faq6_pergunta': 'Qual é o lanche mais popular?',
        'faq6_resposta': 'Nosso X-Tudo Burger é o favorito dos clientes! É um hambúrguer completo com ingredientes autênticos brasileiros.'
    },
    'en-US': {
        'inicio': 'Home',
        'cardapio': 'Menu',
        'sobre': 'About',
        'contato': 'Contact',
        'slogan': 'BRAZILIAN FLAVOR IN THE USA',
        'descricao': 'Try the most delicious sandwiches with that authentic Brazilian seasoning, in a cozy environment that will make you feel at home.',
        'cardapio_completo': 'FULL MENU',
        'sabor_real': 'REAL FLAVOR',
        'sabor_real_desc': 'Handcrafted sandwiches prepared with selected ingredients',
        'ambiente_brasileiro': 'BRAZILIAN ATMOSPHERE',
        'ambiente_brasileiro_desc': 'Music, decoration and that warm Brazilian service',
        'pratos_exclusivos': 'EXCLUSIVE DISHES',
        'pratos_exclusivos_desc': 'Unique combinations only found here at King Bites',
        'nossos_destaques': 'OUR HIGHLIGHTS',
        'salgadinhos_brasileiros_gallery': 'Brazilian snacks',
        'x_tudo_hamburguer': 'X-Tudo burger',
        'frango_com_fritas': 'Chicken with fries',
        'pizza_e_lanche': 'Pizza and sandwich',
        'o_que_clientes_dizem': 'WHAT OUR CUSTOMERS SAY',
        'testemunho_cliente': 'The best Brazilian burger I\'ve ever had outside Brazil. I felt at home!',
        'nome_cliente': '- John Smith, Customer since 2023',
        'slogan_final': 'KING BITES. WHERE FLAVOR IS TRULY KING.',
        'experimente_agora': 'TRY IT NOW',
        'cardapio_king_bites': 'KING BITES MENU',
        'menu_subtitulo': 'Try our handcrafted sandwiches with authentic Brazilian flavor',
        'especial': 'SPECIAL',
        'combo_especial_king_bites': 'KING BITES SPECIAL COMBO',
        'combo_especial_desc': 'Try our exclusive combo with 3 X-Everything Burgers, grilled Calabrian sausage (spicy Brazilian style), 25 mini Brazilian savory snacks (coxinha, risoles and more) and loaded fries. Perfect for sharing with friends and family!',
        'fazer_pedido': 'ORDER NOW',
        'todos': 'All',
        'hamburgueres': 'Burgers',
        'combos': 'Combos',
        'salgadinhos': 'Snacks',
        'bebidas': 'Drinks',
        'hamburgueres_brasileiros': 'BRAZILIAN BURGERS',
        'hamburgueres_desc': 'Our handcrafted burgers are prepared in authentic Brazilian style, with fresh, high-quality ingredients. Each burger comes with a unique combination of flavors that will transport you directly to the streets of Brazil.',
        'combos_acompanhamentos': 'COMBOS AND SIDES',
        'combos_desc': 'Our combos are perfect for sharing or for those who want to experience a variety of flavors. With options that combine our favorite sandwiches with delicious sides, you will have a complete gastronomic experience.',
        'salgadinhos_brasileiros': 'BRAZILIAN SNACKS',
        'salgadinhos_desc': 'Savory snacks are an essential part of Brazilian cuisine. We offer a variety of traditional options, from chicken coxinhas to sausage rolls, all prepared with authentic recipes brought directly from Brazil.',
        'bebidas_titulo': 'DRINKS',
        'bebidas_desc': 'Complete your meal with our selection of beverages, including Brazilian sodas like the famous Guaraná, which offers a unique and refreshing flavor to accompany your favorite sandwiches.',
        'o_que_clientes_dizem_menu': 'WHAT OUR CUSTOMERS SAY',
        'experimente_sabor': 'EXPERIENCE THE AUTHENTIC TASTE OF BRAZIL',
        'experimente_sabor_desc': 'Visit King Bites today or order online to try the best Brazilian sandwiches in the United States!',
        'pedir_agora': 'ORDER NOW',
        'sobre_king_bites': 'ABOUT KING BITES',
        'nossa_historia': 'OUR STORY',
        'historia_paragrafo1': 'King Bites was born from a true passion for Brazilian cuisine. We believe each bite should be unforgettable — that\'s why we use fresh ingredients, juicy meats, and original recipes that turn anyone into a fan.',
        'historia_paragrafo2': 'Our mission is simple: deliver a unique experience where flavor is king. From the soft bread to the handcrafted burger and our homemade sauces, every detail is made with care so you always leave satisfied.',
        'historia_paragrafo3': 'More than just a burger joint, we are a meeting point for those who love good food, a relaxed atmosphere, and first-class service.',
        'historia_paragrafo4': 'King Bites. Where flavor is king.',
        'nossa_missao': 'OUR MISSION',
        'missao_statement': 'To serve high-quality artisanal food, providing a flavorful, welcoming, and memorable experience for each customer — always with fresh ingredients, excellent service, and passion in every detail.',
        'ingredientes_frescos': 'Fresh Ingredients',
        'ingredientes_frescos_desc': 'From the producer directly to your table, we guarantee freshness and quality in every meal',
        'chefs_especializados': 'Specialized Chefs',
        'chefs_especializados_desc': 'Artisanal preparation with exclusive techniques and knowledge of Brazilian cuisine',
        'feito_com_amor': 'Made with Love',
        'feito_com_amor_desc': 'Each sandwich is prepared with care, as if we were cooking for our own family',
        'cliente_rei': 'Customer is King',
        'cliente_rei_desc': 'Each customer is treated like royalty — with respect, care, and high-quality service',
        'excelencia_sempre': 'Excellence Always',
        'excelencia_sempre_desc': 'From our kitchen to your table, we seek nothing less than excellence in everything we do',
        'sabores_brasil': 'Flavors of Brazil',
        'sabores_brasil_desc': 'We bring the authenticity of Brazilian gastronomy to the heart of the United States',
        'nossa_trajetoria': 'OUR JOURNEY',
        'ideia': 'The Idea',
        'ideia_desc': 'King Bites begins as a dream to bring true Brazilian flavors to the USA.',
        'primeiros_passos': 'First Steps',
        'primeiros_passos_desc': 'Opening of the first store, with just a small menu of burgers and Brazilian snacks.',
        'expansao_cardapio': 'Menu Expansion',
        'expansao_cardapio_desc': 'We added new items to the menu, including more options for Brazilian snacks and sandwiches.',
        'reconhecimento_local': 'Local Recognition',
        'reconhecimento_local_desc': 'King Bites is recognized as one of the best Brazilian burger joints in the region.',
        'presente_futuro': 'Present and Future',
        'presente_futuro_desc': 'We continue to grow and innovate, always maintaining the authenticity and flavor that made us famous.',
        'venha_experimentar': 'COME AND TRY',
        'venha_experimentar_desc': 'We are waiting for you to experience the best of Brazilian cuisine in the United States. Handcrafted burgers, traditional snacks, and much more!',
        'ver_cardapio': 'VIEW MENU',
        'fale_conosco': 'CONTACT US',
        'contato_subtitulo': 'Have a question or suggestion? Send us a message and we will get back to you as soon as possible!',
        'info_contato': 'Contact Information',
        'endereco': 'Address',
        'endereco_valor': '550 Ferry Street Everett, MA, EUA',
        'telefone': 'Phone',
        'telefone_valor': '+1 (781) 475-7872',
        'email': 'Email',
        'email_valor': 'renata.souza.coelho@hotmail.com',
        'horario_funcionamento': 'Opening Hours',
        'horario_dias_semana': 'Mon - Wed: 11am to 10pm',
        'horario_fim_semana': 'Thur - Sat: 12pm to 8pm',
        'redes_sociais': 'Social Media',
        'localizacao_mapa': 'King Bites Location',
        'envie_mensagem': 'SEND A MESSAGE',
        'seu_nome': 'Your Name',
        'nome_placeholder': 'Enter your full name',
        'seu_email': 'Your Email',
        'email_placeholder': 'example@email.com',
        'sua_mensagem': 'Your Message',
        'mensagem_placeholder': 'How can we help? Write your message here...',
        'enviando': 'Sending...',
        'enviar_mensagem': 'Send Message',
        'mensagem_sucesso': 'Message sent successfully! We will get back to you soon.',
        'mensagem_erro': 'Unable to send your message. Please try again later.',
        'perguntas_frequentes': 'FREQUENTLY ASKED QUESTIONS',
        'faq1_pergunta': 'What are the opening hours of King Bites?',
        'faq1_resposta': 'We are open Monday to Saturday, from 11am to 10pm, and on Sundays from 12pm to 8pm.',
        'faq2_pergunta': 'Do you offer vegetarian options?',
        'faq2_resposta': 'Yes! We have several vegetarian options on our menu, including plant-based sandwiches and cheese snacks.',
        'faq3_pergunta': 'Can I place orders for events?',
        'faq3_resposta': 'Absolutely! We offer catering services for events of all sizes. Contact us at least 48 hours in advance to discuss options.',
        'faq4_pergunta': 'Do you make deliveries?',
        'faq4_resposta': 'Yes, we deliver through DoorDash and also offer pickup options.',
        'faq5_pergunta': 'Are the ingredients imported from Brazil?',
        'faq5_resposta': 'We use a combination of ingredients imported from Brazil and high-quality local ingredients to create the authentic Brazilian experience.',
        'faq6_pergunta': 'What is the most popular sandwich?',
        'faq6_resposta': 'Our X-Tudo Burger is the customer favorite! It is a complete burger with authentic Brazilian ingredients.'
    }
};

export const LanguageProvider: React.FC<{children: ReactNode}> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>('pt-BR');
    const [translations, setTranslations] = useState(translationMap['pt-BR']);

    useEffect(() => {
        const savedLanguage = localStorage.getItem('language') as Language | null;
        if (savedLanguage && (savedLanguage === 'pt-BR' || savedLanguage === 'en-US')) {
            setLanguageState(savedLanguage);
            setTranslations(translationMap[savedLanguage]);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        setTranslations(translationMap[lang]);
        localStorage.setItem('language', lang);
        document.documentElement.lang = lang;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, translations }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage deve ser usado dentro de um LanguageProvider');
    }
    return context;
};